name: "02 - Workflow Events"
on:
    push:
    pull_request:
    schedule :
      - cron: '*/5 * * * *'  # Runs daily at midnight UTC
    workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
        - name: Show the trigger
          run: "echo Event name: ${{ github.event_name }} "
